#!/bin/bash
#
# Save me to /etc/init.d/memcached
# And add me to system start
# chmod +x memcached
# chkconfig --add memcached
# chkconfig --level 35 memcached on
#
# chkconfig: - 80 12
# description: Distributed memory caching daemon
#
 
source /etc/rc.d/init.d/functions
 
### Default variables
PORT="11211"
USER="www-data"
MAXCONN="2048"
CACHESIZE="2048"
OPTIONS=""
 
RETVAL=0
PIDFILE=/var/run/memcached/memcached.$PORT.pid
prog="/usr/local/memcached/bin/memcached"
desc="`basename $prog` port: ${PORT}"
 
[ -d /var/run/memcached ] || mkdir /var/run/memcached
chown ${USER}:root /var/run/memcached

start() {
    echo -n $"Starting $desc"
    daemon $prog -d -p $PORT -u $USER -c $MAXCONN -m $CACHESIZE -P ${PIDFILE} $OPTIONS
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/memcached.${PORT}
    return $RETVAL
}
 
stop() {
    echo -n $"Shutting down $desc"
    killproc -p ${PIDFILE} $prog
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/memcached.${PORT}
    return $RETVAL
}
 
restart() {
    stop
    start
}
 
reload() {
    echo $"Reloading $desc does not support"
#    echo -n $"Reloading $desc"
#    killproc -p ${PIDFILE} $prog -HUP
#    RETVAL=$?
#    echo
    return $RETVAL
}
 
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  condrestart)
    [ -e /var/lock/subsys/$prog ] && restart
    RETVAL=$?
    ;;
  reload)
    reload
    ;;
  status)
    status $prog
    RETVAL=$?
    ;;
   *)
    echo $"Usage: $0 {start|stop|restart|condrestart|status}"
    RETVAL=1
esac
exit $RETVAL
